### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by at-wat** [pion/.goassets#169]
We use https://github.com/google/go-licenses to check all dependencies of our product have allowed licenses.
Currently, license can't be automatically detected in many pion packages.

```
E0519 02:38:40.946603    3890 library.go:122] Failed to find license for github.com/pion/ice/v2: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.3.4" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.3.4"
E0519 02:38:41.147227    3890 library.go:122] Failed to find license for github.com/pion/ice/v2/internal/atomic: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.3.4/internal/atomic" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.3.4"
E0519 02:38:41.165343    3890 library.go:122] Failed to find license for github.com/pion/ice/v2/internal/fakenet: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.3.4/internal/fakenet" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.3.4"
E0519 02:38:41.179924    3890 library.go:122] Failed to find license for github.com/pion/ice/v2/internal/stun: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.3.4/internal/stun" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.3.4"
E0519 02:38:41.216210    3890 library.go:122] Failed to find license for github.com/pion/stun: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/stun@v0.5.2" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/stun@v0.5.2"
E0519 02:38:41.248084    3890 library.go:122] Failed to find license for github.com/pion/stun/internal/hmac: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/stun@v0.5.2/internal/hmac" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/stun@v0.5.2"
E0519 02:38:41.455293    3890 library.go:122] Failed to find license for github.com/pion/webrtc/v3: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3"
E0519 02:38:41.503584    3890 library.go:122] Failed to find license for github.com/pion/srtp/v2: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/srtp/v2@v2.0.14" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/srtp/v2@v2.0.14"
E0519 02:38:41.529922    3890 library.go:122] Failed to find license for github.com/pion/webrtc/v3/internal/fmtp: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3/internal/fmtp" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3"
E0519 02:38:41.553269    3890 library.go:122] Failed to find license for github.com/pion/webrtc/v3/internal/mux: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3/internal/mux" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3"
E0519 02:38:41.578211    3890 library.go:122] Failed to find license for github.com/pion/webrtc/v3/internal/util: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3/internal/util" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3"
E0519 02:38:41.604190    3890 library.go:122] Failed to find license for github.com/pion/webrtc/v3/pkg/media: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3/pkg/media" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3"
E0519 02:38:41.627958    3890 library.go:122] Failed to find license for github.com/pion/webrtc/v3/pkg/rtcerr: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3/pkg/rtcerr" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3"
E0519 02:38:42.477853    3890 library.go:122] Failed to find license for github.com/pion/webrtc/v3/pkg/media/samplebuilder: cannot find a known open source license for "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3/pkg/media/samplebuilder" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.2.3"
```

**Comment by at-wat** [comment]
@stv0g I think it's related to your change

**Comment by at-wat** [comment]
Also, pkg.go.dev requires substance of LICENSE file in each repository.
https://pkg.go.dev/github.com/pion/ice/v2
![image](https://github.com/pion/.goassets/assets/8390204/80846d98-34c5-4a71-9a47-e2a6be6061a5)

**Comment by at-wat** [comment]
In some repository, @Sean-Der seems restored LICENSE file, but copyright holder name is currently missing

**Comment by Sean-Der** [comment]
Thanks for catching @at-wat ! I noticed this also via https://gophers.slack.com/archives/CAK2124AG/p1684429971162799

I think @stv0g has a plan to fix this tomorrow. If you don't have time I am happy to make the change also. Can we switch from symlink back to a LICENSE file in all these repos?

**Comment by stv0g** [comment]
Okay, this is now fixed across all Pion repos. Sorry for the mess

**Comment by at-wat** [comment]
Thanks for fixing!

**Comment by Sean-Der** [comment]
@stv0g you have no reason to apologize!

You have been doing an amazing job at cleaning up Pion. We have accumulated a lot of tech debt. Your involvement is making the project so much better.

‘Mistakes’ only happen because someone is trying to make things better. When you ‘play it safe’ that is when innovation stops!

Keep up the great work. I am a fan

**Comment by at-wat** [comment]
btw, I'll create ice and stun release tag to make the latest versions having license file

**Comment by at-wat** [comment]
https://github.com/pion/rtp/issues/231
pion/rtp seems not fixed yet

**Comment by stv0g** [comment]
Fixed in https://github.com/pion/rtp/issues/231
